services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ordeon
      TYPEORM_SYNCHRONIZE: 'true'
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordeon
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  whodb:
    image: clidey/whodb:latest
    ports:
      - 8080:8080
    volumes:
      - whodb_data:/var/lib/whodb/data
  
volumes:
  db_data:
    driver: local
  whodb_data:
    driver: local